version: '3.7'

services:
  consul-server:
    image: consul:1.9.3
    container_name: consul-server
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'

networks:
  consul:
    driver: bridge